apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrcode-template
  namespace: cesieats-services
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: qrcode-template
  template:
    metadata:
      labels:
        app: qrcode-template
    spec:
      containers:
        - name: qrcode-template
          image: kilme/qrcode-template:$IMAGE_VERSION
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-qrcode
  namespace: cesieats-services
spec:
  selector:
    app: qrcode-template
  ports:
    - name: http
      protocol: TCP
      port: 3000
      nodePort: 30199
  type: NodePort